# Generated by Django 4.2.1 on 2023-06-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_coffee_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='pice',
            new_name='price',
        ),
    ]
